before_script:
  - yum install -y python-flake8 epel-release
  - yum install python-nose python-pip
  - pip install -r /builds/dankrs/requirements.txt

check_lint:
  script:
    - flake8 -v *.py */*.py 
    - nosetests -v
