before_script:
  - yum install -y epel-release
  - yum install -y python-pip
  - pip install --upgrade pip
  - pip install -r /builds/dankrs/forecastio/requirements.txt

check_lint:
  script:
    - flake8 *.py */*.py 
run_tests:
  script:
    - nosetests -v
